// <auto-generated />
using AmigoSecreto.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AmigoSecreto.Migrations
{
    [DbContext(typeof(AmigoSecretoContext))]
    [Migration("20241206231033_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AmigoSecreto.Entities.GroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("AmigoSecreto.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("ValidationType", "Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LestName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SecretSantaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("SecretSantaId")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("AmigoSecreto.Entities.UserEntity", b =>
                {
                    b.HasOne("AmigoSecreto.Entities.GroupEntity", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId");

                    b.HasOne("AmigoSecreto.Entities.UserEntity", "SecretSanta")
                        .WithOne()
                        .HasForeignKey("AmigoSecreto.Entities.UserEntity", "SecretSantaId");

                    b.Navigation("Group");

                    b.Navigation("SecretSanta");
                });

            modelBuilder.Entity("AmigoSecreto.Entities.GroupEntity", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
